### ISSUE TITLE
Recurring events not shown?

### ISSUE THREAD

**Issue by unhammer** [legalnonsense/org-timed-alerts#1]
Related: https://github.com/alphapapa/org-ql/issues/159

**Comment by legalnonsense** [comment]
Should be fixed in the repeat branch. 

Added org-ql predicate to look for repeated times. https://github.com/legalnonsense/org-timed-alerts/blob/d3ce176f8fa68e21a673275e745a41c37390da1f/org-timed-alerts.el#L183

Added loop to update repeated times to current using ts.el: https://github.com/legalnonsense/org-timed-alerts/blob/d3ce176f8fa68e21a673275e745a41c37390da1f/org-timed-alerts.el#L246

Added a check to the parser to call the update function if the timestamp has a repeat:
https://github.com/legalnonsense/org-timed-alerts/blob/d3ce176f8fa68e21a673275e745a41c37390da1f/org-timed-alerts.el#L286

Easier to to it this way than to find the built-in agenda functions that do this. 

Have not tested much but seems to be working.

**Comment by unhammer** [comment]
> Easier to to it this way than to find the built-in agenda functions that do this.

I did it the hard way by trying to understand org-agenda.el, I wonder which one of us wasted the least time =P (`(org-time-string-to-absolute org-ts-string from-day 'future)` gives the first absolute day on or after from-day, c.f. [usage here](https://github.com/unhammer/org-upcoming-modeline/blob/27fb74f9e7480c40b95af2170f5d427fd21e0953/org-upcoming-modeline.el#L248-L258))

**Comment by legalnonsense** [comment]
Yours is definitely cleaner! Seems like my hackier solution is working, so will keep it until the urge to clean it up arises. Totally forgot about repeat events when I wrote this so thank you for pointing it out. Think it's all working now but keeping this open until I confirm. Your upcoming event package looks good. Also been using org-mru-clock for a long time now.
