### ISSUE TITLE
void-function org-ql--defpred

### ISSUE THREAD

**Issue by akurth** [legalnonsense/org-timed-alerts#3]
Hi,

thanks for this useful package.

org-ql--defpred has apparently been renamed to org-ql-defpred in recent org-ql versions; at least in 20201213.1358 (installed from MELPA).

**Comment by legalnonsense** [comment]
Thanks for letting me know. Any chance you know how to check for org-ql's package version? I did a quick look and there (remarkably?) doesn't seem to be a built-in way to do that? Otherwise I guess I should just upgrade and make the newest melpa version a requirement? Will figure out in the next few days but if anyone knows please tell me how to handle this best.

**Comment by legalnonsense** [comment]
Should be fixed in latest commit.
